---
title: "&#39;Catch&#39; non può trovarsi all'esterno di un &#39;provare a&#39; istruzione"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 346852cbd5693fbafe25413291ae284de3692875
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 05/04/2018
---
# <a name="39catch39-cannot-appear-outside-a-39try39-statement"></a>&#39;Catch&#39; non può trovarsi all'esterno di un &#39;provare a&#39; istruzione
`Catch` deve figurare all'interno di un blocco di istruzioni `Try...Catch...Finally` . Nel blocco `Catch` è presente un'istruzione `Try` non necessaria oppure l'istruzione `Catch` si trova al di fuori dei limiti del blocco `Try` corrispondente.  
  
 **ID errore:** BC30380  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1.  Eliminare l'istruzione `Catch` se non è necessaria oppure inserirla all'interno di un blocco di istruzioni `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
