---
title: "&#39;Exit Try&#39; può trovarsi solo all'interno di un &#39;provare a&#39; istruzione"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: a33f5750a0ba8f833e623101467327635bf0c8d8
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 05/04/2018
ms.locfileid: "33614482"
---
# <a name="39exit-try39-can-only-appear-inside-a-39try39-statement"></a>&#39;Exit Try&#39; può trovarsi solo all'interno di un &#39;provare a&#39; istruzione
`Exit Try` può trovarsi solo all'interno di un'istruzione del blocco `Try` . È presente un'istruzione `Exit Try` ridondante oppure l'istruzione `Exit Try` si trova al di fuori dei limiti del blocco `Try` corrispondente.  
  
 **ID errore:** BC30393  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1.  Individuare e rimuovere l'istruzione `Exit Try` non necessaria.  
  
2.  Spostare il `Exit Try` istruzione nella posizione appropriata all'interno del codice.  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
