---
title: "&#39; Genera &#39; l'istruzione non può omettere l'operando all'esterno di un &#39; Catch &#39; istruzione o all'interno un &#39; Infine &#39; istruzione"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords: BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 5fa3be0ca47a4158b3abeef9801148e3f19d3b36
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 01/19/2018
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39; Genera &#39; l'istruzione non può omettere l'operando all'esterno di un &#39; Catch &#39; istruzione o all'interno un &#39; Infine &#39; istruzione
Le istruzioni`Throw` di fuori dell'istruzione `Catch` devono fornire il nome di un oggetto eccezione.  
  
 **ID errore:** BC30666  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1.  Specificare il nome di un oggetto eccezione derivato da `System.Exception`.  
  
2.  Ristrutturare il codice in modo che l'istruzione `Throw` si trovi in un blocco `Catch` .  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione Throw](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Classe di eccezione in Visual Basic](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Eccezioni e gestione degli errori in Visual Basic](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
