---
title: "&#39;Generare&#39; l'istruzione non è possibile omettere l'operando all'esterno di un &#39;Catch&#39; istruzione o all'interno un &#39;Finally&#39; istruzione"
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: e426e0d7af685fae82d8dc64a95803bdacb543e0
ms.sourcegitcommit: 8c2ece71e54f46aef9a2153540d0bda7e74b19a9
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 09/11/2018
ms.locfileid: "44360849"
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39;Generare&#39; l'istruzione non è possibile omettere l'operando all'esterno di un &#39;Catch&#39; istruzione o all'interno un &#39;Finally&#39; istruzione
Le istruzioni`Throw` di fuori dell'istruzione `Catch` devono fornire il nome di un oggetto eccezione.  
  
 **ID errore:** BC30666  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1.  Specificare il nome di un oggetto eccezione derivato da `System.Exception`.  
  
2.  Ristrutturare il codice in modo che l'istruzione `Throw` si trovi in un blocco `Catch` .  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione Throw](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Classe di eccezione in Visual Basic](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Eccezioni e gestione degli errori in Visual Basic](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
