---
title: "&#39; Catch &#39; blocco non raggiunto perché &#39; &lt;nome1&gt;&#39; eredita da &#39;&lt; Nome2&gt;&#39;"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords: BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: "12"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: c21d4d662f4741916e308278a41a84d40f92454a
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 11/21/2017
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39; Catch &#39; blocco non raggiunto perché &#39; &lt;nome1&gt;&#39; eredita da &#39;&lt; Nome2&gt;&#39;
Un blocco `Catch` all'interno del codice non viene mai raggiunto.  
  
 Per impostazione predefinita, si tratta di un messaggio di avviso. Per altre informazioni su come nascondere gli avvisi o considerarli come errori, vedere [configurazione degli avvisi in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **ID errore:** BC42029  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
-   Rimuovere il blocco `Catch` estraneo.  
  
## <a name="see-also"></a>Vedere anche  
 [Procedura: testare il codice con un blocco Try... Blocco catch in Visual Basic](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
